## Clock signal (W5) - Even if not used, BSV modules expect it
set_property PACKAGE_PIN W5 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports CLK]

## Reset (Center Button U18) - BSV RST_N is Active Low
set_property PACKAGE_PIN T1 [get_ports RST_N]
set_property IOSTANDARD LVCMOS33 [get_ports RST_N]

## Switches (Inputs: a[0-3], b[0-3], cin)
set_property PACKAGE_PIN V17 [get_ports {a_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_0}]
set_property PACKAGE_PIN V16 [get_ports {a_1}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_1}]
set_property PACKAGE_PIN W16 [get_ports {a_2}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_2}]
set_property PACKAGE_PIN W17 [get_ports {a_3}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_3}]

set_property PACKAGE_PIN W15 [get_ports {b_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_0}]
set_property PACKAGE_PIN V15 [get_ports {b_1}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_1}]
set_property PACKAGE_PIN W14 [get_ports {b_2}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_2}]
set_property PACKAGE_PIN W13 [get_ports {b_3}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_3}]

set_property PACKAGE_PIN V2 [get_ports cin]
set_property IOSTANDARD LVCMOS33 [get_ports cin]

## LEDs (Outputs: sum[0-3], carry_out)
set_property PACKAGE_PIN U16 [get_ports {sum_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {sum_0}]
set_property PACKAGE_PIN E19 [get_ports {sum_1}]
set_property IOSTANDARD LVCMOS33 [get_ports {sum_1}]
set_property PACKAGE_PIN U19 [get_ports {sum_2}]
set_property IOSTANDARD LVCMOS33 [get_ports {sum_2}]
set_property PACKAGE_PIN V19 [get_ports {sum_3}]
set_property IOSTANDARD LVCMOS33 [get_ports {sum_3}]
set_property PACKAGE_PIN W18 [get_ports carry_out]
set_property IOSTANDARD LVCMOS33 [get_ports carry_out]

set_property IOSTANDARD LVCMOS33 [get_ports {a[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sum[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sum[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sum[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sum[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports RDY_carry_out]
set_property IOSTANDARD LVCMOS33 [get_ports RDY_sum]
set_property PACKAGE_PIN V17 [get_ports {a[0]}]
set_property PACKAGE_PIN V16 [get_ports {a[1]}]
set_property PACKAGE_PIN W16 [get_ports {a[2]}]
set_property PACKAGE_PIN W17 [get_ports {a[3]}]
set_property PACKAGE_PIN W15 [get_ports {b[0]}]
set_property PACKAGE_PIN V15 [get_ports {b[1]}]
set_property PACKAGE_PIN W14 [get_ports {b[2]}]
set_property PACKAGE_PIN W13 [get_ports {b[3]}]
set_property PACKAGE_PIN U16 [get_ports {sum[0]}]
set_property PACKAGE_PIN E19 [get_ports {sum[1]}]
set_property PACKAGE_PIN U19 [get_ports {sum[2]}]
set_property PACKAGE_PIN V19 [get_ports {sum[3]}]

set_property PACKAGE_PIN L1 [get_ports RDY_carry_out]
set_property PACKAGE_PIN P1 [get_ports RDY_sum]
